name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Helllooo"
          echo "Hello World Zare"

      - name: Print Goodbye
        run: echo "Bye bye z"
